-- MySQL Workbench Synchronization
-- Generated: 2025-09-05 11:28
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: netom

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `SUDAE` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE IF NOT EXISTS `SUDAE`.`USUARIO` (
  `idUSUARIO` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `matricula` VARCHAR(15) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `tipo` TINYINT(4) NOT NULL COMMENT '1 - Servidor AE\n2 - Professor\n3 - Aluno',
  `curso` VARCHAR(255) NULL DEFAULT NULL,
  `turma` CHAR(5) NULL DEFAULT NULL COMMENT 'TI-30\nTE-20\nTA-10',
  PRIMARY KEY (`idUSUARIO`),
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC) ,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `SUDAE`.`ATRASO` (
  `idATRASO` INT(11) NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `idAluno` INT(11) NOT NULL,
  `idServidor` INT(11) NOT NULL,
  `notificado` CHAR(1) NULL DEFAULT NULL,
  `motivo` TEXT NOT NULL,
  `observ` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idATRASO`),
  INDEX `fk_ATRASO_USUARIO1_idx` (`idAluno` ASC) ,
  INDEX `fk_ATRASO_USUARIO2_idx` (`idServidor` ASC) ,
  CONSTRAINT `fk_ATRASO_USUARIO1`
    FOREIGN KEY (`idAluno`)
    REFERENCES `SUDAE`.`USUARIO` (`idUSUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ATRASO_USUARIO2`
    FOREIGN KEY (`idServidor`)
    REFERENCES `SUDAE`.`USUARIO` (`idUSUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `SUDAE`.`ATA` (
  `idATA` INT(11) NOT NULL,
  `data` DATETIME NOT NULL,
  `assunto` VARCHAR(100) NOT NULL,
  `anotacoes` TEXT NOT NULL,
  `encaminhamentos` TEXT NULL DEFAULT NULL,
  `idRedator` INT(11) NOT NULL,
  PRIMARY KEY (`idATA`),
  INDEX `fk_ATA_USUARIO_idx` (`idRedator` ASC) ,
  CONSTRAINT `fk_ATA_USUARIO`
    FOREIGN KEY (`idRedator`)
    REFERENCES `SUDAE`.`USUARIO` (`idUSUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `SUDAE`.`PARTICIPANTES` (
  `idAta` INT(11) NOT NULL,
  `idUSUARIO` INT(11) NOT NULL,
  `dataRegistro` DATETIME NOT NULL COMMENT 'S- Sim\nN- Não',
  `assinatura` CHAR(1) NOT NULL DEFAULT 'N',
  `dataAssinatura` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`idAta`, `idUSUARIO`),
  INDEX `fk_ATA_has_USUARIO_USUARIO1_idx` (`idUSUARIO` ASC) ,
  INDEX `fk_ATA_has_USUARIO_ATA1_idx` (`idAta` ASC) ,
  CONSTRAINT `fk_ATA_has_USUARIO_ATA1`
    FOREIGN KEY (`idAta`)
    REFERENCES `SUDAE`.`ATA` (`idATA`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ATA_has_USUARIO_USUARIO1`
    FOREIGN KEY (`idUSUARIO`)
    REFERENCES `SUDAE`.`USUARIO` (`idUSUARIO`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
